import 'package:latlong2/latlong.dart';

enum ChiangRaiArea {
  thasud,
  central,
  other,
}

class GasStation {
  final String id;
  final String name;
  final String brand;
  final LatLng location;
  final List<String> amenities;
  final List<String> fuelTypes;
  final String district;
  final ChiangRaiArea area;

  GasStation({
    required this.id,
    required this.name,
    required this.brand,
    required this.location,
    required this.amenities,
    required this.fuelTypes,
    required this.district,
    required this.area,
  });

  bool isInArea(ChiangRaiArea targetArea) => area == targetArea;
  bool isInDistrict(String targetDistrict) => district == targetDistrict;
}

final List<GasStation> mockGasStations = [
  // --- อำเภอเมืองเชียงราย ---
  GasStation(
    id: '1',
    name: 'PT Station Chiang Rai 4',
    brand: 'PT',
    location: const LatLng(19.9090, 99.8320),
    amenities: ['Punthai Coffee', 'MaxMart', 'ห้องน้ำสะอาด'],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'E20', 'ดีเซล'],
    district: 'เมืองเชียงราย',
    area: ChiangRaiArea.central,
  ),
  GasStation(
    id: '2',
    name: 'PT Gas Station Chiangrai2 (Punthai)',
    brand: 'PT',
    location: const LatLng(19.9150, 99.8400),
    amenities: ['Punthai Coffee', 'MaxMart', 'ห้องน้ำสะอาด'],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'แก๊สโซฮอล์ 91', 'ดีเซล'],
    district: 'เมืองเชียงราย',
    area: ChiangRaiArea.central,
  ),
  GasStation(
    id: '3',
    name: 'PTT Station (Petrol+EV)',
    brand: 'PTT',
    location: const LatLng(19.9200, 99.8250),
    amenities: ['7-Eleven', 'Cafe Amazon', 'ห้องน้ำสะอาด', 'ร้านอาหาร'],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'E20', 'ดีเซล', 'EV Charging'],
    district: 'เมืองเชียงราย',
    area: ChiangRaiArea.central,
  ),
  GasStation(
    id: '4',
    name: 'PT Gas Station',
    brand: 'PT',
    location: const LatLng(19.8950, 99.8300),
    amenities: ['MaxMart', 'ห้องน้ำสะอาด'],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'ดีเซล'],
    district: 'เมืองเชียงราย',
    area: ChiangRaiArea.central,
  ),
  GasStation(
    id: '5',
    name: 'PT STATION - บายพาสวงแหวนตะวันออกเชียงราย',
    brand: 'PT',
    location: const LatLng(19.8800, 99.8500),
    amenities: [
      'Punthai Coffee',
      'MaxMart',
      'ห้องน้ำสะอาด',
      'ที่จอดรถกว้างขวาง'
    ],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'E20', 'ดีเซล'],
    district: 'เมืองเชียงราย',
    area: ChiangRaiArea.central,
  ),
  GasStation(
    id: '6',
    name: 'PT Chiang Rai1',
    brand: 'PT',
    location: const LatLng(19.9000, 99.8450),
    amenities: ['MaxMart', 'ห้องน้ำสะอาด'],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'แก๊สโซฮอล์ 91', 'ดีเซล'],
    district: 'เมืองเชียงราย',
    area: ChiangRaiArea.central,
  ),
  GasStation(
    id: '7',
    name: 'PTT Station Doi Saken',
    brand: 'PTT',
    location: const LatLng(19.9120, 99.8550),
    amenities: ['7-Eleven', 'Cafe Amazon', 'ห้องน้ำสะอาด'],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'E20', 'ดีเซล'],
    district: 'เมืองเชียงราย',
    area: ChiangRaiArea.central,
  ),
  GasStation(
    id: '8',
    name: 'PT Station',
    brand: 'PT',
    location: const LatLng(19.8900, 99.8200),
    amenities: ['ห้องน้ำสะอาด'],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'ดีเซล'],
    district: 'เมืองเชียงราย',
    area: ChiangRaiArea.central,
  ),
  GasStation(
    id: '9',
    name: 'Shell',
    brand: 'Shell',
    location: const LatLng(19.9050, 99.8350),
    amenities: ['Deli Cafe', 'Select Shop', 'ห้องน้ำสะอาด'],
    fuelTypes: [
      'V-Power แก๊สโซฮอล์ 95',
      'V-Power ดีเซล',
      'ฟิวเซฟ แก๊สโซฮอล์ 95'
    ],
    district: 'เมืองเชียงราย',
    area: ChiangRaiArea.central,
  ),
  GasStation(
    id: '10',
    name: 'Bangchak - Chatchai Highway Ltd.,Part.',
    brand: 'Bangchak',
    location: const LatLng(19.9250, 99.8300),
    amenities: ['Inthanin Coffee', 'Mini Big C', 'ห้องน้ำสะอาด'],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'E20', 'ดีเซล'],
    district: 'เมืองเชียงราย',
    area: ChiangRaiArea.central,
  ),
  GasStation(
    id: '11',
    name: 'ปั๊มน้ำมันบางจาก - ห้างหุ้นส่วนจำกัด พานพิเศษออยล์',
    brand: 'Bangchak',
    location: const LatLng(19.8850, 99.8400),
    amenities: ['ร้านของชำ', 'ห้องน้ำสะอาด'],
    fuelTypes: ['แก๊สโซฮอล์ 91', 'แก๊สโซฮอล์ 95', 'ดีเซล'],
    district: 'เมืองเชียงราย',
    area: ChiangRaiArea.central,
  ),
  GasStation(
    id: '12',
    name: 'ปั๊มน้ำมัน',
    brand: 'Independent',
    location: const LatLng(19.8950, 99.8100),
    amenities: ['ร้านค้าชุมชน'],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'ดีเซล'],
    district: 'เมืองเชียงราย',
    area: ChiangRaiArea.central,
  ),
  GasStation(
    id: '13',
    name: 'Bangchak - Srichaiyant Oil Co., Ltd.(BR1)',
    brand: 'Bangchak',
    location: const LatLng(19.9100, 99.8600),
    amenities: ['Inthanin Coffee', 'ห้องน้ำสะอาด'],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'E20', 'E85', 'ดีเซล'],
    district: 'เมืองเชียงราย',
    area: ChiangRaiArea.central,
  ),

  // --- อำเภอแม่ลาว ---
  GasStation(
    id: '14',
    name: 'ปั๊มน้ำมัน พีที แม่ลาว 1',
    brand: 'PT',
    location: const LatLng(19.7400, 99.7200),
    amenities: ['MaxMart', 'ห้องน้ำสะอาด'],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'ดีเซล'],
    district: 'แม่ลาว',
    area: ChiangRaiArea.other,
  ),
  GasStation(
    id: '15',
    name: 'PTT Station (Petrol+EV)',
    brand: 'PTT',
    location: const LatLng(19.7350, 99.7250),
    amenities: ['7-Eleven', 'Cafe Amazon', 'ห้องน้ำสะอาด'],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'E20', 'ดีเซล', 'EV Charging'],
    district: 'แม่ลาว',
    area: ChiangRaiArea.other,
  ),

  // --- อำเภอเชียงแสน ---
  GasStation(
    id: '16',
    name: 'PTT Station ปตท.เชียงแสน (น้ำมัน+EV)',
    brand: 'PTT',
    location: const LatLng(20.2700, 100.0800),
    amenities: ['7-Eleven', 'Cafe Amazon', 'ห้องน้ำสะอาด'],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'E20', 'ดีเซล', 'EV Charging'],
    district: 'เชียงแสน',
    area: ChiangRaiArea.other,
  ),
  GasStation(
    id: '17',
    name: 'PT',
    brand: 'PT',
    location: const LatLng(20.2750, 100.0850),
    amenities: ['ห้องน้ำ'],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'ดีเซล'],
    district: 'เชียงแสน',
    area: ChiangRaiArea.other,
  ),

  // --- อำเภอแม่สาย ---
  GasStation(
    id: '18',
    name: 'PTT Station (Petrol+EV)',
    brand: 'PTT',
    location: const LatLng(20.4300, 99.8800),
    amenities: ['7-Eleven', 'Cafe Amazon', 'ห้องน้ำสะอาด', 'ร้านอาหาร'],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'E20', 'ดีเซล', 'EV Charging'],
    district: 'แม่สาย',
    area: ChiangRaiArea.other,
  ),
  GasStation(
    id: '19',
    name: 'PT STATION สาขาแม่สาย1',
    brand: 'PT',
    location: const LatLng(20.4250, 99.8850),
    amenities: ['Punthai Coffee', 'MaxMart', 'ห้องน้ำสะอาด'],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'E20', 'ดีเซล'],
    district: 'แม่สาย',
    area: ChiangRaiArea.other,
  ),
  GasStation(
    id: '20',
    name: 'คอสโม ออยล์ สาขา เวียงหอม',
    brand: 'Cosmo',
    location: const LatLng(20.4150, 99.8900),
    amenities: ['ห้องน้ำ'],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'ดีเซล'],
    district: 'แม่สาย',
    area: ChiangRaiArea.other,
  ),
  GasStation(
    id: '21',
    name: 'Cosmo (Yod Nuea Petroleum)',
    brand: 'Cosmo',
    location: const LatLng(20.4200, 99.8950),
    amenities: ['ร้านของชำ'],
    fuelTypes: ['แก๊สโซฮอล์ 91', 'ดีเซล'],
    district: 'แม่สาย',
    area: ChiangRaiArea.other,
  ),
  GasStation(
    id: '22',
    name: 'เอ็ม ซี แก๊ส แอนด์ ปิโตรเคมิคัลล์',
    brand: 'LPG',
    location: const LatLng(20.4350, 99.8700),
    amenities: ['ห้องน้ำ'],
    fuelTypes: ['LPG'],
    district: 'แม่สาย',
    area: ChiangRaiArea.other,
  ),
  GasStation(
    id: '23',
    name: 'Bangchak',
    brand: 'Bangchak',
    location: const LatLng(20.4400, 99.8750),
    amenities: ['Inthanin Coffee', 'Mini Big C'],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'E20', 'ดีเซล'],
    district: 'แม่สาย',
    area: ChiangRaiArea.other,
  ),
  GasStation(
    id: '24',
    name: 'ปั๊ม แอลพีจี',
    brand: 'LPG',
    location: const LatLng(20.4100, 99.8800),
    amenities: [],
    fuelTypes: ['LPG'],
    district: 'แม่สาย',
    area: ChiangRaiArea.other,
  ),
  GasStation(
    id: '25',
    name: 'ร้านดำยานยนต์ /เหมืองแดง ซ.8 หน้าแม่สายแมนชั่น',
    brand: 'Independent',
    location: const LatLng(20.4320, 99.8850),
    amenities: ['บริการซ่อมบำรุง'],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'ดีเซล'],
    district: 'แม่สาย',
    area: ChiangRaiArea.other,
  ),
  GasStation(
    id: '26',
    name: 'หนึ่ง การช่างแม่สาย',
    brand: 'Independent',
    location: const LatLng(20.4280, 99.8880),
    amenities: ['อู่ซ่อมรถ'],
    fuelTypes: ['ดีเซล'],
    district: 'แม่สาย',
    area: ChiangRaiArea.other,
  ),

  // --- อำเภอพาน ---
  GasStation(
    id: '27',
    name: 'PTT Station',
    brand: 'PTT',
    location: const LatLng(19.5500, 99.7400),
    amenities: ['7-Eleven', 'Cafe Amazon', 'ห้องน้ำสะอาด', 'ร้านอาหาร'],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'แก๊สโซฮอล์ 91', 'E20', 'ดีเซล'],
    district: 'พาน',
    area: ChiangRaiArea.other,
  ),
  GasStation(
    id: '28',
    name: 'ปั้มน้ำมันคาลเท็กซ์ อ.พาน',
    brand: 'Caltex',
    location: const LatLng(19.5550, 99.7450),
    amenities: ['ห้องน้ำสะอาด', 'Mini Mart'],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'ดีเซล (Techron)'],
    district: 'พาน',
    area: ChiangRaiArea.other,
  ),
  GasStation(
    id: '29',
    name: 'ปั๊ม PT สาขา พาน1',
    brand: 'PT',
    location: const LatLng(19.5450, 99.7350),
    amenities: ['Punthai Coffee', 'MaxMart', 'ห้องน้ำสะอาด'],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'E20', 'ดีเซล'],
    district: 'พาน',
    area: ChiangRaiArea.other,
  ),

  // --- อำเภอเวียงชัย ---
  GasStation(
    id: '30',
    name: 'ปั้มน้ำมัน พีที เวียงชัย3',
    brand: 'PT',
    location: const LatLng(19.8810, 99.8820),
    amenities: ['MaxMart', 'ห้องน้ำสะอาด'],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'ดีเซล'],
    district: 'เวียงชัย',
    area: ChiangRaiArea.other,
  ),
  GasStation(
    id: '31',
    name: 'PT STATION สาขาเวียงชัย2',
    brand: 'PT',
    location: const LatLng(19.8750, 99.8900),
    amenities: ['Punthai Coffee', 'MaxMart', 'ห้องน้ำสะอาด'],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'ดีเซล'],
    district: 'เวียงชัย',
    area: ChiangRaiArea.other,
  ),
  GasStation(
    id: '32',
    name: 'ปั้มน้ำมัน (Don Sila)',
    brand: 'Independent',
    location: const LatLng(19.8650, 99.8700),
    amenities: ['ร้านของชำ'],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'ดีเซล'],
    district: 'เวียงชัย',
    area: ChiangRaiArea.other,
  ),
  GasStation(
    id: '33',
    name: 'PT Gas Station',
    brand: 'PT',
    location: const LatLng(19.8900, 99.8850),
    amenities: ['ห้องน้ำสะอาด'],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'ดีเซล'],
    district: 'เวียงชัย',
    area: ChiangRaiArea.other,
  ),
  GasStation(
    id: '34',
    name: 'Gas station',
    brand: 'Independent',
    location: const LatLng(19.8800, 99.8750),
    amenities: [],
    fuelTypes: ['ดีเซล'],
    district: 'เวียงชัย',
    area: ChiangRaiArea.other,
  ),
  GasStation(
    id: '35',
    name: 'Caltex Purethai Wiang Chai',
    brand: 'Caltex',
    location: const LatLng(19.8850, 99.8800),
    amenities: ['Mini Mart', 'ห้องน้ำสะอาด'],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'ดีเซล'],
    district: 'เวียงชัย',
    area: ChiangRaiArea.other,
  ),
  GasStation(
    id: '36',
    name: 'สถานีบริการน้ำมัน Cosmo สหกรณ์',
    brand: 'Cosmo',
    location: const LatLng(19.8950, 99.8900),
    amenities: ['ร้านของชำ', 'ห้องน้ำสะอาด'],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'ดีเซล'],
    district: 'เวียงชัย',
    area: ChiangRaiArea.other,
  ),
  GasStation(
    id: '37',
    name: 'Gas station (Pha Ngam)',
    brand: 'Independent',
    location: const LatLng(19.8550, 99.9050),
    amenities: ['ร้านค้าชุมชน'],
    fuelTypes: ['แก๊สโซฮอล์ 91', 'ดีเซล'],
    district: 'เวียงชัย',
    area: ChiangRaiArea.other,
  ),
  GasStation(
    id: '38',
    name: 'ปั้มบีโฮม',
    brand: 'Independent',
    location: const LatLng(19.8600, 99.8750),
    amenities: ['ห้องน้ำ'],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'ดีเซล'],
    district: 'เวียงชัย',
    area: ChiangRaiArea.other,
  ),

  // --- อำเภอพญาเม็งราย ---
  GasStation(
    id: '39',
    name: 'PTT Station ปตท.พญาเม็งราย',
    brand: 'PTT',
    location: const LatLng(19.8450, 100.1500),
    amenities: ['7-Eleven', 'Cafe Amazon', 'ห้องน้ำสะอาด'],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'E20', 'ดีเซล'],
    district: 'พญาเม็งราย',
    area: ChiangRaiArea.other,
  ),
  GasStation(
    id: '40',
    name: 'ปั๊มน้ำมัน PT',
    brand: 'PT',
    location: const LatLng(19.8400, 100.1550),
    amenities: ['MaxMart', 'ห้องน้ำสะอาด'],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'ดีเซล'],
    district: 'พญาเม็งราย',
    area: ChiangRaiArea.other,
  ),
  GasStation(
    id: '41',
    name: 'ปั๊มน้ำมันบางจาก - สหกรณ์การเกษตร พญาเม็งราย จำกัด สาขาไม้ยา',
    brand: 'Bangchak',
    location: const LatLng(19.8350, 100.1450),
    amenities: ['ร้านของชำ', 'ห้องน้ำสะอาด'],
    fuelTypes: ['แก๊สโซฮอล์ 91', 'ดีเซล'],
    district: 'พญาเม็งราย',
    area: ChiangRaiArea.other,
  ),
  GasStation(
    id: '42',
    name: 'ปั๊มน้ำมันบางจาก - สหกรณ์การเกษตร พญาเม็งราย จำกัด',
    brand: 'Bangchak',
    location: const LatLng(19.8480, 100.1520),
    amenities: ['Inthanin Coffee', 'Mini Big C', 'ห้องน้ำสะอาด'],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'E20', 'ดีเซล'],
    district: 'พญาเม็งราย',
    area: ChiangRaiArea.other,
  ),
  GasStation(
    id: '43',
    name: 'วิบูลย์ออยล์',
    brand: 'Independent',
    location: const LatLng(19.8500, 100.1600),
    amenities: ['ร้านค้าชุมชน'],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'ดีเซล'],
    district: 'พญาเม็งราย',
    area: ChiangRaiArea.other,
  ),
  GasStation(
    id: '44',
    name: 'Gas station (Mai Ya)',
    brand: 'Independent',
    location: const LatLng(19.8300, 100.1400),
    amenities: [],
    fuelTypes: ['ดีเซล'],
    district: 'พญาเม็งราย',
    area: ChiangRaiArea.other,
  ),
  GasStation(
    id: '45',
    name: 'Gas station (Yang Hom)',
    brand: 'Independent',
    location: const LatLng(19.8600, 100.1700),
    amenities: [],
    fuelTypes: ['ดีเซล'],
    district: 'พญาเม็งราย',
    area: ChiangRaiArea.other,
  ),
  GasStation(
    id: '46',
    name: 'ปั๊มน้ำมัน',
    brand: 'Independent',
    location: const LatLng(19.8420, 100.1480),
    amenities: ['ห้องน้ำ'],
    fuelTypes: ['แก๊สโซฮอล์ 91', 'ดีเซล'],
    district: 'พญาเม็งราย',
    area: ChiangRaiArea.other,
  ),
  GasStation(
    id: '47',
    name: 'Petrol',
    brand: 'Independent',
    location: const LatLng(19.8550, 100.1650),
    amenities: [],
    fuelTypes: ['แก๊สโซฮอล์ 95'],
    district: 'พญาเม็งราย',
    area: ChiangRaiArea.other,
  ),
  GasStation(
    id: '48',
    name: 'เม็งรายการยาง&ตรอ.',
    brand: 'Independent',
    location: const LatLng(19.8470, 100.1580),
    amenities: ['บริการตรวจสภาพรถ', 'ปะยาง'],
    fuelTypes: ['ดีเซล'],
    district: 'พญาเม็งราย',
    area: ChiangRaiArea.other,
  ),

  // --- อำเภอขุนตาล ---
  GasStation(
    id: '49',
    name: 'PT, ขุนตาล',
    brand: 'PT',
    location: const LatLng(19.8550, 100.2500),
    amenities: ['MaxMart', 'ห้องน้ำสะอาด'],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'ดีเซล'],
    district: 'ขุนตาล',
    area: ChiangRaiArea.other,
  ),
  GasStation(
    id: '50',
    name: 'Gas station (Pa Tan)',
    brand: 'Independent',
    location: const LatLng(19.8600, 100.2450),
    amenities: ['ร้านของชำ'],
    fuelTypes: ['แก๊สโซฮอล์ 91', 'ดีเซล'],
    district: 'ขุนตาล',
    area: ChiangRaiArea.other,
  ),
  GasStation(
    id: '51',
    name: 'Petrol (Ta)',
    brand: 'Independent',
    location: const LatLng(19.8500, 100.2550),
    amenities: [],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'ดีเซล'],
    district: 'ขุนตาล',
    area: ChiangRaiArea.other,
  ),
  GasStation(
    id: '52',
    name: 'Au Watchara Yon',
    brand: 'Independent',
    location: const LatLng(19.8650, 100.2400),
    amenities: ['อู่ซ่อมรถ'],
    fuelTypes: ['ดีเซล'],
    district: 'ขุนตาล',
    area: ChiangRaiArea.other,
  ),
  GasStation(
    id: '53',
    name: 'ปั๊มน้ำมันPT Promjai Energy',
    brand: 'PT',
    location: const LatLng(19.8450, 100.2600),
    amenities: ['ห้องน้ำสะอาด'],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'ดีเซล'],
    district: 'ขุนตาล',
    area: ChiangRaiArea.other,
  ),

  // --- อำเภอแม่ฟ้าหลวง ---
  GasStation(
    id: '54',
    name: 'PTT Station (Petrol+EV) Maefahluang',
    brand: 'PTT',
    location: const LatLng(20.2500, 99.8000),
    amenities: ['7-Eleven', 'Cafe Amazon', 'ห้องน้ำสะอาด'],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'E20', 'ดีเซล', 'EV Charging'],
    district: 'แม่ฟ้าหลวง',
    area: ChiangRaiArea.other,
  ),

  // --- อำเภอเชียงของ ---
  GasStation(
    id: '55',
    name: 'PTT Station เชียงของ',
    brand: 'PTT',
    location: const LatLng(20.2600, 100.4000),
    amenities: ['7-Eleven', 'Cafe Amazon', 'ห้องน้ำสะอาด', 'ร้านอาหาร'],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'E20', 'ดีเซล'],
    district: 'เชียงของ',
    area: ChiangRaiArea.other,
  ),
  GasStation(
    id: '56',
    name: 'Esso Gas Station',
    brand: 'Esso',
    location: const LatLng(20.2650, 100.4050),
    amenities: ['Mini Mart', 'ห้องน้ำสะอาด'],
    fuelTypes: ['ซูพรีมพลัส แก๊สโซฮอล์ 95', 'ดีเซล'],
    district: 'เชียงของ',
    area: ChiangRaiArea.other,
  ),
  GasStation(
    id: '57',
    name: 'Bangchak - Nakornpasubcharoen Co.,Ltd.',
    brand: 'Bangchak',
    location: const LatLng(20.2550, 100.3950),
    amenities: ['Inthanin Coffee', 'Mini Big C', 'ห้องน้ำสะอาด'],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'E20', 'ดีเซล'],
    district: 'เชียงของ',
    area: ChiangRaiArea.other,
  ),
  GasStation(
    id: '58',
    name: 'Cosmo (Konghathai Limited Partnership)',
    brand: 'Cosmo',
    location: const LatLng(20.2700, 100.4100),
    amenities: ['ร้านของชำ', 'ห้องน้ำสะอาด'],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'ดีเซล'],
    district: 'เชียงของ',
    area: ChiangRaiArea.other,
  ),
  GasStation(
    id: '59',
    name: 'ทางเชื่อมปั้มน้ำมัน',
    brand: 'Independent',
    location: const LatLng(20.2500, 100.3900),
    amenities: [],
    fuelTypes: ['ดีเซล'],
    district: 'เชียงของ',
    area: ChiangRaiArea.other,
  ),
  GasStation(
    id: '60',
    name: '78 ปิโตรเลี่ยม',
    brand: 'Independent',
    location: const LatLng(20.2750, 100.4150),
    amenities: ['ร้านค้าชุมชน'],
    fuelTypes: ['แก๊สโซฮอล์ 91', 'ดีเซล'],
    district: 'เชียงของ',
    area: ChiangRaiArea.other,
  ),
  GasStation(
    id: '61',
    name: 'PTT (Por.Charoen Ban Kaen Limited Partnership)',
    brand: 'PTT',
    location: const LatLng(20.2450, 100.3850),
    amenities: ['7-Eleven', 'ห้องน้ำสะอาด'],
    fuelTypes: ['แก๊สโซฮอล์ 95', 'ดีเซล'],
    district: 'เชียงของ',
    area: ChiangRaiArea.other,
  ),
  GasStation(
    id: '62',
    name: 'ปั๊มแก๊ส LPG เชียงของ',
    brand: 'LPG',
    location: const LatLng(20.2800, 100.4200),
    amenities: ['ห้องน้ำ'],
    fuelTypes: ['LPG'],
    district: 'เชียงของ',
    area: ChiangRaiArea.other,
  ),
];
