// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIv0l_nCE-hMbXIcacuBwgb_w6NWLMKXM',
    appId: '1:78932977850:web:c24f1dc3d757a7c0e57a83',
    messagingSenderId: '78932977850',
    projectId: 'fuelnear',
    authDomain: 'fuelnear.firebaseapp.com',
    databaseURL: 'https://fuelnear-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fuelnear.firebasestorage.app',
    measurementId: 'G-828KQLCCMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUi_bPEhaTXAdxuJML4Ww6B7ZUL9_TV9U',
    appId: '1:78932977850:android:ba9f478cd2844b00e57a83',
    messagingSenderId: '78932977850',
    projectId: 'fuelnear',
    databaseURL: 'https://fuelnear-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fuelnear.firebasestorage.app',
  );
}
